### ISSUE TITLE
maxPollingInterval on host.json doesn't seem to take effect anymore

### ISSUE THREAD

**Issue by jeremy001181** [Scooletz/QueueBatch#13]
I would like to make my function to poll the target queue every 100ms, so to achieve that I used to use `maxPollingInterval` settings and set it to `00:00:00.100`, with `QueueBatch` installed, this doesn't seem to work anymore. any idea?

Thanks

**Comment by Scooletz** [comment]
Unfortunately, the only way to configure `QueueBatch` for now is the attribute. The pooling interval, etc. is configured in the [BindingProvider](https://github.com/Scooletz/QueueBatch/blob/107e2f6447bd32203698cff9dd8a1aec7c2e0e21/src/QueueBatch/Impl/BindingProvider.cs#L57).

If you'd like to have it, it would require a PR with some tests for passing the configuration in both ways.

**Comment by jeremy001181** [comment]
Tried with the attribute approach, works like a charm, happy to close
