### ISSUE TITLE
Number of function executions

### ISSUE THREAD

**Issue by jeremy001181** [Scooletz/QueueBatch#14]
Hey @Scooletz 

Could be a silly question, lets say my function receives a batch of 32 messages as an example, when it comes to calculate Azure Function pricing, will it be counted as executed 32 times or only once? My guess is latter, just want to be sure.
Thanks

**Comment by Scooletz** [comment]
@jeremy001181 I assume that you're asking about the case when the queue contains 32 messages and the function trigger obtains all of them in one call of `GetMessages`. This will result in a single function execution with a batch of 32 messages being past to your functions. This is why it's named `QueueBatch` 😉 

If it addresses your question, please close the issue.

**Comment by jeremy001181** [comment]
fantastic...just to be certain :) closed
