### ISSUE TITLE
Messages in a batch marked as processed get picked up again if others cause exception

### ISSUE THREAD

**Issue by jeremy001181** [Scooletz/QueueBatch#15]
Hey

I have scenario where handles messages in parallel, so the way I have this done is to wrap them in their own `Task` which calls `MarkAsProcessed` at the end, then `await Task.WhenAll(allTasks)`. 

It works fine with happy path, however if one of task causes exception, the function will again pick up all processed messages which seems wrong to me. so I had a look at the source code, and realize it doesn't do`batch.Complete` in case where exception occurred
https://github.com/Scooletz/QueueBatch/blob/df6591d936d04d3f145df2a33c538b5cd8365759/src/QueueBatch/Impl/Listener.cs#L122

Do you think it is a valid feature/bug to add/fix? if so, I don't mind create a PR for it.

Thanks

**Comment by Scooletz** [comment]
My reasoning for this was the following:

1. The batch is passed as a whole to a function
1. Every message is marked as processed separately
1. If an exception is thrown, it is thrown for the function arguments, ergo, for the batch
1. It means that there was something faulty on the batch level, not a single message level
1. The execution needs to be retried

We could consider changing this behavior, but it would be a breaking change. I see no strong arguments for one side or another, so I'd leave it as it is unless strong arguments are provided. One argument that I see to keep the behavior as it is now, is an easy way to "just throw and retry whole batch", which seems natural to me.

**Comment by jeremy001181** [comment]
That means the consumers of messages have to be idempotent all the way
down, which can't be achieved in my case where some of messages will get
transformed into notifications at the downstream somewhere, and we can't send
duplicate notification.

**Comment by Scooletz** [comment]
This is always the case with Azure Storage Queues. You can have either _at-most-once_ or _at-least-once_. There's no way to receive and send a message in an atomic way. You need to use Azure Service Bus to do it.

**Comment by jeremy001181** [comment]
I am not sure how changing to service bus would help, I know it has duplicate detection feature which can guarantee exactly once delivery at sender, but we are talking about consumer side right?

Also let's say I have 32 messages in a queue, if a function keeps crashing at the 32nd message (weird data issue), all 1-31 messages in the same batch will end up in poison queue even they are perfectly valid because the `DequeueCount` exceeds the maximum, and this behaviour wouldn't happen if use native queue trigger, Doesn't it seem wrong? It doesn't seem fair for the other 31 messages as they just unfortunately get picked up in the same batch as the bad guy.

I could put a try-catch in the function to handle the exception from the 32nd  message but I lose the built-in retry feature

**Comment by Scooletz** [comment]
Let me clarify. With ASB you can receive and send atomically, but yes, you're right, eventually the received need to dedup as well. There's nothing like `exactly-once`, we can only move it as close as possible to the receiving part.

This is a good point. From a single message perspective, there's a flaw, but from the batch point of view, it's not so clear. I think that at least this should be configurable, for instance on the attribute level (with opt-in for confirming all that were processed).

Let me think about it. If you want to sketch a proposal, I'm 👍

**Comment by jeremy001181** [comment]
Even from batch perspective, I couldn't think of any business case in real
world that it has a value, fail or success as a batch

After all, every single messages in queue is independent, there is no
correlation or ordering between them, even they are, it cannot be supported
by queue due to the nature of queue trigger process , because of that, it
limits the execution at client side cannot have a transact operation and
must treat them as individual independent, so for that reason, I think,
even it is a batch process, function should be responsible for delivering
at message level.

**Comment by Scooletz** [comment]
I'm not taking about a business case, but rather "just throwing" in the first line of a func. Still, this could be qualified as "all messages are not ACKed, and should be retried". I do agree, that in case where a message is marked as completed, it can be completed no matter if the batch as a whole throw an exception. 

This requires some rework on the listener in the lines pointed above and tests covering (at least once) that when a func throws, messages that were ACKed are ACKed.

Do you want to take it @jeremy001181 ?

**Comment by jeremy001181** [comment]
Yes, I will create a PR for it

**Comment by Scooletz** [comment]
Sorry for keeping it that long. The #16 has been merged. Eventually, I fall back to setting this option to false anyway as I agree with your reasoning about the buggish behavior. Anyway, it's published as 1.2.0 on nuget. Thank you!
