### ISSUE TITLE
Idea: generalize the queue lib to allow for plugging in other queue technologies

### ISSUE THREAD

**Issue by wachulski** [Scooletz/QueueBatch#7]
First, a piece of solid work! Two things:

1. Looking at `src/QueueBatch` abstractions, they don't know anything about Azure Cloud queues. Neither does `src/QueueBatch/Impl/Queues/FastCloudQueue.cs` (just a quick glance, I suppose there are more). Do you think it's reasonable to make the lib more pluggable, etc. `QueueBatch.Abstractions` along with `QueueBatch.Azure`, `QueueBatch.Aws`, `QueueBatch.RabbitMq` etc.? This could make the whole a highly performant solution of any queue provider out there.

2. I'm also wondering whether it's worthwhile as it could also be that the performance improvement trick is strictly related with Azure queue specific stuff. Is it? Well, from what you said in https://github.com/Scooletz/QueueBatch#why it shouldn't be the case.

Just an idea, what do you think?

**Comment by Scooletz** [comment]
Hey, thank you @wachulski and thanks for raising this. The answers below were rephrased 3 times after me having an internal discussion with myself 😉 

Having a batch and being able to amortize costs of accessing resources is a huge gain, especially when you pay for a transaction. Then, with batching, you just divide numbers :) For ASQ, it's even bigger as the current client is written in an extremely allocate'y way and the `FastCloudQueue` is the answer for ASQ poor performance. `FastCloudQueue` is not a generic tool, although a generic tool could be potentially extracted from it. 

On having `QueueBatch.Abstractions` It might be a good idea to have a core "batch" functionality, but this would require a lot of work, not only to provide a common public seam for any messaging, but also test it, verify it and again, ensure that we don't drop the ball in any case. 

I do agree, that on the higher level, one could think of providing a similar seam to the `IAsyncCollector` and `ICollector` and build all the needed pieces: converters, etc. to enable a user to use them in a transparent way. This again, requires so much work and looks like a core concern that could be potentially addressed on the WebJobs SDK level, leaving up to the user how single items are dispatched.

Having this said, it's unlikely that I'll move `QueueBatch` move into a general direction. This would require a lot of work, that probably I cannot afford. I'll keep it small and efficient though for people willing to use ASQ.

**Comment by Scooletz** [comment]
If my comment answers your question, consider closing this issue.

Thanks 🤗

**Comment by wachulski** [comment]
Thanks for thorough elaboration on the initial intent and further plans. Well, I conclude the abstraction would likely end up as a thin layer of leaky concepts, hard to adapt in particular implementations. And it'd be still specialized implementations that provide gains (if done well).

Nevertheless, good clarification, thx @Scooletz
