### ISSUE TITLE
Is the IMessageBatch.MarkAsProcessed (msg) thread safe?

### ISSUE THREAD

**Issue by jeremy001181** [Scooletz/QueueBatch#8]
So that I can process multiple messages in parallel and also mark them processed in parallel.

**Comment by Scooletz** [comment]
A good catch! Currently it is not as it uses `HashSet<>` and marking as processed uses just the hashset underneath

https://github.com/Scooletz/QueueBatch/blob/39992c9fffa55c4e0da26eec968f01bfd41bb1e1/src/QueueBatch/Impl/MessageBatch.cs#L30

If you'd like to have ability to do in in parallel, I'd be more than happy to accept a PR.

**Comment by jeremy001181** [comment]
@Scooletz just created a pull request 
https://github.com/Scooletz/QueueBatch/pull/10

**Comment by Scooletz** [comment]
Awesome @jeremy001181 👍 
I've got to run some errands 🎄 ☃️ but this should be reviewed and hopefully merged by the end of year (at latest!).

**Comment by Scooletz** [comment]
Addressed by #10 and #11
